version: '3.4'

services:
  banktradingservice:
    image: ${DOCKER_REGISTRY-}banktradingservice
    build:
      context: .
      dockerfile: BankTradingService/Dockerfile
  banktradingservice-consumer:
    image: ${DOCKER_REGISTRY-}banktradingserviceconsumer
    build:
      context: .
      dockerfile: BankTradingService.Consumer/Dockerfile
  banktradingservice-db:
    container_name: banktradingservice-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Str0ngPa$w0rd"
      ACCEPT_EULA: "Y"
